#!/usr/bin/env python3
"""
prep.py — Pre-open reconnaissance. Runs well before the bell (no deadline
pressure), so the two time-critical jobs at 8:45 and 9:00 CT have nothing left
to do but look at candles.

Steps
  1. Refresh the tradable universe from the Nasdaq Trader symbol directory
     (all US-listed common stock, minus ETFs / warrants / units / rights /
     preferreds / test issues). ~5,600 names.
  2. Pull 6 months of daily bars for each and compute the level set
     (range high/low, nearest swing low beneath, nearest swing high above,
     ATR14, 20d average volume).
  3. Apply the liquidity floor. Optionable-in-practice means a name that
     actually trades: price >= $3 and 20-day average dollar volume >= $5M.
  4. Write data/cache/levels-YYYY-MM-DD.json.

Usage:
    python -m sneak.prep                 # full run
    python -m sneak.prep --limit 300     # quick smoke test
    python -m sneak.prep --date 2026-08-14   # rebuild levels as of a past day
"""

from __future__ import annotations

import argparse
import io
import json
import re
import sys
import time
from datetime import date, datetime, timedelta
from pathlib import Path

import requests

from . import yahoo
from .levels import compute_levels

ROOT = Path(__file__).resolve().parent.parent
CACHE_DIR = ROOT / "data" / "cache"
UNIVERSE_FILE = ROOT / "data" / "universe.txt"

NASDAQ_TRADED = "https://www.nasdaqtrader.com/dynamic/SymDir/nasdaqtraded.txt"

MIN_PRICE = 3.00
MIN_DOLLAR_VOL = 5_000_000

_EXCLUDE_NAME = re.compile(
    r"\b(warrants?|rights?|units?|depositary|preferred|debenture|"
    r"subordinated|notes? due|convertible note)\b",
    re.I,
)


# ── universe ─────────────────────────────────────────────────────────────────

def fetch_symbol_directory() -> list[str]:
    """All US-listed common-stock tickers from the Nasdaq Trader directory."""
    r = requests.get(
        NASDAQ_TRADED, timeout=60, headers={"User-Agent": yahoo.UA}
    )
    r.raise_for_status()
    lines = [l for l in io.StringIO(r.text) if "|" in l]
    rows = [l.rstrip("\n").split("|") for l in lines]
    hdr = rows[0]
    out = []
    for row in rows[1:]:
        if len(row) != len(hdr):
            continue
        d = dict(zip(hdr, row))
        if d.get("Nasdaq Traded") != "Y":
            continue
        if d.get("Test Issue") == "Y" or d.get("ETF") == "Y":
            continue
        if d.get("Listing Exchange") not in ("N", "Q", "A", "P", "Z"):
            continue
        if _EXCLUDE_NAME.search(d.get("Security Name", "")):
            continue
        sym = d.get("Symbol", "")
        # Plain 1-5 letter roots only: drops warrant/unit/class suffixes that
        # Yahoo addresses differently anyway.
        if not re.fullmatch(r"[A-Z]{1,5}", sym):
            continue
        out.append(sym)
    return sorted(set(out))


# ── main ─────────────────────────────────────────────────────────────────────

def run(limit: int | None = None, as_of: date | None = None, workers: int = 24) -> dict:
    t0 = time.time()
    today = as_of or yahoo.now_et().date()

    print(f"[prep] {datetime.now().isoformat(timespec='seconds')} building universe…", flush=True)
    try:
        symbols = fetch_symbol_directory()
        UNIVERSE_FILE.parent.mkdir(parents=True, exist_ok=True)
        UNIVERSE_FILE.write_text(
            "# Auto-generated by sneak.prep — US-listed common stock, pre-liquidity-filter.\n"
            f"# Refreshed {today.isoformat()} · {len(symbols)} symbols\n"
            + "\n".join(symbols)
            + "\n"
        )
    except Exception as e:
        print(f"[prep] symbol directory failed ({e}); falling back to cached universe", flush=True)
        symbols = [
            l.strip()
            for l in UNIVERSE_FILE.read_text().splitlines()
            if l.strip() and not l.startswith("#")
        ]
    if limit:
        symbols = symbols[:limit]
    print(f"[prep] universe: {len(symbols)} symbols", flush=True)

    # 6mo of daily bars gives ~126 sessions: enough for ATR14 + a 60-bar swing window.
    print("[prep] pulling daily bars…", flush=True)
    daily = yahoo.charts(symbols, rng="6mo", interval="1d", workers=workers)
    print(f"[prep] daily bars for {len(daily)}/{len(symbols)} symbols "
          f"({time.time()-t0:.0f}s)", flush=True)

    levels, skipped_illiquid, skipped_short = {}, 0, 0
    for sym, bars in daily.items():
        lv = compute_levels(sym, bars, today=today)
        if lv is None:
            skipped_short += 1
            continue
        if lv["prev_close"] < MIN_PRICE or lv["avg_dollar_vol20"] < MIN_DOLLAR_VOL:
            skipped_illiquid += 1
            continue
        levels[sym] = lv

    payload = {
        "built_at": datetime.now(yahoo.CT).isoformat(timespec="seconds"),
        "for_session": today.isoformat(),
        "universe_size": len(symbols),
        "with_data": len(daily),
        "tradable": len(levels),
        "filters": {"min_price": MIN_PRICE, "min_dollar_vol20": MIN_DOLLAR_VOL},
        "levels": levels,
    }

    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    out = CACHE_DIR / f"levels-{today.isoformat()}.json"
    out.write_text(json.dumps(payload))
    print(
        f"[prep] tradable {len(levels)} · dropped {skipped_illiquid} illiquid, "
        f"{skipped_short} short-history · {time.time()-t0:.0f}s → {out.name}",
        flush=True,
    )
    return payload


def load_levels(day: date) -> dict | None:
    p = CACHE_DIR / f"levels-{day.isoformat()}.json"
    if not p.exists():
        return None
    return json.loads(p.read_text())


def main() -> int:
    ap = argparse.ArgumentParser(description="Pre-open level cache builder")
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--date", type=str, default=None, help="YYYY-MM-DD (backfill)")
    ap.add_argument("--workers", type=int, default=24)
    a = ap.parse_args()
    as_of = datetime.strptime(a.date, "%Y-%m-%d").date() if a.date else None
    run(limit=a.limit, as_of=as_of, workers=a.workers)
    return 0


if __name__ == "__main__":
    sys.exit(main())
